// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.35.0
// source: services/ok-grpc/ok.proto

package okv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OKRequest) Reset() {
	*x = OKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_ok_grpc_ok_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKRequest) ProtoMessage() {}

func (x *OKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_ok_grpc_ok_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKRequest.ProtoReflect.Descriptor instead.
func (*OKRequest) Descriptor() ([]byte, []int) {
	return file_services_ok_grpc_ok_proto_rawDescGZIP(), []int{0}
}

type OKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OKResponse) Reset() {
	*x = OKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_ok_grpc_ok_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKResponse) ProtoMessage() {}

func (x *OKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_ok_grpc_ok_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKResponse.ProtoReflect.Descriptor instead.
func (*OKResponse) Descriptor() ([]byte, []int) {
	return file_services_ok_grpc_ok_proto_rawDescGZIP(), []int{1}
}

var File_services_ok_grpc_ok_proto protoreflect.FileDescriptor

var file_services_ok_grpc_ok_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x6b, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x6b, 0x2e,
	0x76, 0x31, 0x22, 0x0b, 0x0a, 0x09, 0x4f, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x0c, 0x0a, 0x0a, 0x4f, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x36, 0x0a,
	0x09, 0x4f, 0x4b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x02, 0x4f, 0x4b,
	0x12, 0x10, 0x2e, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x4b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x32, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x6b, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x6f, 0x6b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_ok_grpc_ok_proto_rawDescOnce sync.Once
	file_services_ok_grpc_ok_proto_rawDescData = file_services_ok_grpc_ok_proto_rawDesc
)

func file_services_ok_grpc_ok_proto_rawDescGZIP() []byte {
	file_services_ok_grpc_ok_proto_rawDescOnce.Do(func() {
		file_services_ok_grpc_ok_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_ok_grpc_ok_proto_rawDescData)
	})
	return file_services_ok_grpc_ok_proto_rawDescData
}

var file_services_ok_grpc_ok_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_ok_grpc_ok_proto_goTypes = []interface{}{
	(*OKRequest)(nil),  // 0: ok.v1.OKRequest
	(*OKResponse)(nil), // 1: ok.v1.OKResponse
}
var file_services_ok_grpc_ok_proto_depIdxs = []int32{
	0, // 0: ok.v1.OKService.OK:input_type -> ok.v1.OKRequest
	1, // 1: ok.v1.OKService.OK:output_type -> ok.v1.OKResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_ok_grpc_ok_proto_init() }
func file_services_ok_grpc_ok_proto_init() {
	if File_services_ok_grpc_ok_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_ok_grpc_ok_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_ok_grpc_ok_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_ok_grpc_ok_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_ok_grpc_ok_proto_goTypes,
		DependencyIndexes: file_services_ok_grpc_ok_proto_depIdxs,
		MessageInfos:      file_services_ok_grpc_ok_proto_msgTypes,
	}.Build()
	File_services_ok_grpc_ok_proto = out.File
	file_services_ok_grpc_ok_proto_rawDesc = nil
	file_services_ok_grpc_ok_proto_goTypes = nil
	file_services_ok_grpc_ok_proto_depIdxs = nil
}
