// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.35.0
// source: services/ok-grpc/ok.proto

package okv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OKServiceClient is the client API for OKService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OKServiceClient interface {
	OK(ctx context.Context, in *OKRequest, opts ...grpc.CallOption) (*OKResponse, error)
}

type oKServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOKServiceClient(cc grpc.ClientConnInterface) OKServiceClient {
	return &oKServiceClient{cc}
}

func (c *oKServiceClient) OK(ctx context.Context, in *OKRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, "/ok.v1.OKService/OK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OKServiceServer is the server API for OKService service.
// All implementations must embed UnimplementedOKServiceServer
// for forward compatibility
type OKServiceServer interface {
	OK(context.Context, *OKRequest) (*OKResponse, error)
	mustEmbedUnimplementedOKServiceServer()
}

// UnimplementedOKServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOKServiceServer struct {
}

func (UnimplementedOKServiceServer) OK(context.Context, *OKRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OK not implemented")
}
func (UnimplementedOKServiceServer) mustEmbedUnimplementedOKServiceServer() {}

// UnsafeOKServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OKServiceServer will
// result in compilation errors.
type UnsafeOKServiceServer interface {
	mustEmbedUnimplementedOKServiceServer()
}

func RegisterOKServiceServer(s grpc.ServiceRegistrar, srv OKServiceServer) {
	s.RegisterService(&OKService_ServiceDesc, srv)
}

func _OKService_OK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OKServiceServer).OK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ok.v1.OKService/OK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OKServiceServer).OK(ctx, req.(*OKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OKService_ServiceDesc is the grpc.ServiceDesc for OKService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OKService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ok.v1.OKService",
	HandlerType: (*OKServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OK",
			Handler:    _OKService_OK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/ok-grpc/ok.proto",
}
