name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOPRIVATE: github.com/e2engine/*

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.27.x"

      - name: Configure private modules
        run: |
          git config --global \
            url."https://x-access-token:${{ secrets.E2ENGINE_READ_TOKEN }}@github.com/".insteadOf \
            "https://github.com/"

      - name: Verify
        run: make verify
